######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 6 15:16:02 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT+=network
# Input
SOURCES += urlqt.cpp
