######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 6 16:21:17 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . GeneratedFiles
INCLUDEPATH += .
QT+=network
# Input
HEADERS += httpget.h mainwindow.h
FORMS += mainwindow.ui
SOURCES += httpget.cpp main.cpp mainwindow.cpp
RESOURCES += mainwindow.qrc
