######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 6 19:35:15 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT+=network
# Input
HEADERS += httpGet.h
SOURCES += httpGet.cpp logMsg.cpp main.cpp
